require('dotenv').config();

const {GOOGLE_TOKEN} = process.env
const {GOOGLE_SERVICE_ACCOUNT_EMAIL} = process.env

const { GoogleSpreadsheet } = require('google-spreadsheet');

const doc = new GoogleSpreadsheet(
  "1ArZJjg6vKKxASmfEW5mEp4Fm50JEWZUcSdihTWjHJPU"
);

const addNewRow = async (date, summ, sign,ctx, collection) => {
    await doc.useServiceAccountAuth({
      // env var values are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      private_key: process.env.GOOGLE_TOKEN.replace(/(\\r)|(\\n)/g, "\n"),
    });
    await doc.loadInfo();
    const sheet = doc.sheetsByIndex[0];
    if(sign){
        await sheet.addRow({ 'A': date, 'B': summ });
        let rows = await sheet.getRows();
        let rowNumber = rows[rows.length - 1]["_rowNumber"];
        await collection.insertOne({
          messageId: ctx.message.message_id,
          date: date,
          number: summ,
          sign: sign,
          row: rowNumber,
        });
    }
    else{
        await sheet.addRow({ 'A': date, 'C': summ });
        let rows = await sheet.getRows();
        let rowNumber = rows[rows.length - 1]["_rowNumber"];
        await collection.insertOne({
          messageId: ctx.message.message_id,
          date: date,
          number: summ,
          row: rowNumber,
        });
    }
}

const test = async() =>{
    await doc.useServiceAccountAuth({
      client_email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
      private_key: process.env.GOOGLE_TOKEN.replace(/(\\r)|(\\n)/g, "\n"),
    });
    await doc.loadInfo();
    const sheet = doc.sheetsByIndex[0];
    const rows = await sheet.getRows();
    console.log(rows[rows.length - 1]["_rowNumber"]);
}

test()

module.exports = addNewRow;
// addNewRow("06.08", 24350, "minus");


